name: CI

on:
  pull_request:

jobs:
  # Lint the PR title to ensure it follows conventional commit messages
  # release-please relies on conventional commit messages to determine the version bump
  lint-pr-title:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugin
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          package_json_file: plugin/package.json

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: plugin/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile

      - run: pnpm run ci
